# Generated by Django 4.2.17 on 2024-12-12 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetentionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_colour', models.CharField(help_text='A hex colour to represnt this detention', max_length=7)),
                ('severity', models.IntegerField(help_text='The severity of this detention. Higher is more severe')),
                ('default_room', models.CharField(help_text='The default room of this detention', max_length=50)),
                ('first_date_and_time', models.DateTimeField(help_text='The first date and time of this detention. Future detentions will be on the same day of the week')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('preferred_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('warehouse_bk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LatesMonitoring.person')),
            ],
            bases=('LatesMonitoring.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LatesMonitoring.person')),
            ],
            bases=('LatesMonitoring.person',),
        ),
        migrations.CreateModel(
            name='Detention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(help_text='The room of this detention', max_length=50)),
                ('date_and_time', models.DateTimeField()),
                ('detention_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LatesMonitoring.detentiontype')),
                ('staff', models.ManyToManyField(to='LatesMonitoring.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TutorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('assistant_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_head', to='LatesMonitoring.staff')),
                ('head_of_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_of_year', to='LatesMonitoring.staff')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='LatesMonitoring.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInDetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorised', models.BooleanField(default=True)),
                ('total_lates', models.IntegerField(help_text='The total number of lates that lead to this detention')),
                ('attendance', models.TextField(blank=True, choices=[('\\', 'Attended'), ('V', 'Absent with reason'), ('N', 'Absent no reason'), ('-', 'Not recorded')], default='-')),
                ('detention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LatesMonitoring.detention')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LatesMonitoring.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='tutor_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LatesMonitoring.tutorgroup'),
        ),
        migrations.AddField(
            model_name='detentiontype',
            name='default_staff',
            field=models.ForeignKey(blank=True, help_text='The default staff of this detention', null=True, on_delete=django.db.models.deletion.CASCADE, to='LatesMonitoring.staff'),
        ),
    ]
